// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/jmgilman/go/github"
	"sync"
)

// Ensure, that ProviderMock does implement github.Provider.
// If this is not the case, regenerate this file with moq.
var _ github.Provider = &ProviderMock{}

// ProviderMock is a mock implementation of github.Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked github.Provider
//		mockedProvider := &ProviderMock{
//			AddLabelsFunc: func(ctx context.Context, owner string, repo string, number int, labels []string) error {
//				panic("mock out the AddLabels method")
//			},
//			CloseIssueFunc: func(ctx context.Context, owner string, repo string, number int) error {
//				panic("mock out the CloseIssue method")
//			},
//			CreateIssueFunc: func(ctx context.Context, owner string, repo string, opts github.CreateIssueOptions) (*github.IssueData, error) {
//				panic("mock out the CreateIssue method")
//			},
//			CreatePullRequestFunc: func(ctx context.Context, owner string, repo string, opts github.CreatePullRequestOptions) (*github.PullRequestData, error) {
//				panic("mock out the CreatePullRequest method")
//			},
//			CreateRepositoryFunc: func(ctx context.Context, owner string, opts github.CreateRepositoryOptions) (*github.RepositoryData, error) {
//				panic("mock out the CreateRepository method")
//			},
//			GetIssueFunc: func(ctx context.Context, owner string, repo string, number int) (*github.IssueData, error) {
//				panic("mock out the GetIssue method")
//			},
//			GetPullRequestFunc: func(ctx context.Context, owner string, repo string, number int) (*github.PullRequestData, error) {
//				panic("mock out the GetPullRequest method")
//			},
//			GetRepositoryFunc: func(ctx context.Context, owner string, repo string) (*github.RepositoryData, error) {
//				panic("mock out the GetRepository method")
//			},
//			GetWorkflowRunFunc: func(ctx context.Context, owner string, repo string, runID int64) (*github.WorkflowRunData, error) {
//				panic("mock out the GetWorkflowRun method")
//			},
//			GetWorkflowRunJobsFunc: func(ctx context.Context, owner string, repo string, runID int64) ([]*github.WorkflowJobData, error) {
//				panic("mock out the GetWorkflowRunJobs method")
//			},
//			ListIssuesFunc: func(ctx context.Context, owner string, repo string, opts github.ListIssuesOptions) ([]*github.IssueData, error) {
//				panic("mock out the ListIssues method")
//			},
//			ListPullRequestsFunc: func(ctx context.Context, owner string, repo string, opts github.ListPullRequestsOptions) ([]*github.PullRequestData, error) {
//				panic("mock out the ListPullRequests method")
//			},
//			ListRepositoriesFunc: func(ctx context.Context, owner string, opts github.ListOptions) ([]*github.RepositoryData, error) {
//				panic("mock out the ListRepositories method")
//			},
//			ListWorkflowRunsFunc: func(ctx context.Context, owner string, repo string, opts github.ListWorkflowRunsOptions) ([]*github.WorkflowRunData, error) {
//				panic("mock out the ListWorkflowRuns method")
//			},
//			MergePullRequestFunc: func(ctx context.Context, owner string, repo string, number int, opts github.MergePullRequestOptions) error {
//				panic("mock out the MergePullRequest method")
//			},
//			RemoveLabelFunc: func(ctx context.Context, owner string, repo string, number int, label string) error {
//				panic("mock out the RemoveLabel method")
//			},
//			TriggerWorkflowFunc: func(ctx context.Context, owner string, repo string, workflowFileName string, ref string, inputs map[string]interface{}) error {
//				panic("mock out the TriggerWorkflow method")
//			},
//			UpdateIssueFunc: func(ctx context.Context, owner string, repo string, number int, opts github.UpdateIssueOptions) (*github.IssueData, error) {
//				panic("mock out the UpdateIssue method")
//			},
//			UpdatePullRequestFunc: func(ctx context.Context, owner string, repo string, number int, opts github.UpdatePullRequestOptions) (*github.PullRequestData, error) {
//				panic("mock out the UpdatePullRequest method")
//			},
//		}
//
//		// use mockedProvider in code that requires github.Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// AddLabelsFunc mocks the AddLabels method.
	AddLabelsFunc func(ctx context.Context, owner string, repo string, number int, labels []string) error

	// CloseIssueFunc mocks the CloseIssue method.
	CloseIssueFunc func(ctx context.Context, owner string, repo string, number int) error

	// CreateIssueFunc mocks the CreateIssue method.
	CreateIssueFunc func(ctx context.Context, owner string, repo string, opts github.CreateIssueOptions) (*github.IssueData, error)

	// CreatePullRequestFunc mocks the CreatePullRequest method.
	CreatePullRequestFunc func(ctx context.Context, owner string, repo string, opts github.CreatePullRequestOptions) (*github.PullRequestData, error)

	// CreateRepositoryFunc mocks the CreateRepository method.
	CreateRepositoryFunc func(ctx context.Context, owner string, opts github.CreateRepositoryOptions) (*github.RepositoryData, error)

	// GetIssueFunc mocks the GetIssue method.
	GetIssueFunc func(ctx context.Context, owner string, repo string, number int) (*github.IssueData, error)

	// GetPullRequestFunc mocks the GetPullRequest method.
	GetPullRequestFunc func(ctx context.Context, owner string, repo string, number int) (*github.PullRequestData, error)

	// GetRepositoryFunc mocks the GetRepository method.
	GetRepositoryFunc func(ctx context.Context, owner string, repo string) (*github.RepositoryData, error)

	// GetWorkflowRunFunc mocks the GetWorkflowRun method.
	GetWorkflowRunFunc func(ctx context.Context, owner string, repo string, runID int64) (*github.WorkflowRunData, error)

	// GetWorkflowRunJobsFunc mocks the GetWorkflowRunJobs method.
	GetWorkflowRunJobsFunc func(ctx context.Context, owner string, repo string, runID int64) ([]*github.WorkflowJobData, error)

	// ListIssuesFunc mocks the ListIssues method.
	ListIssuesFunc func(ctx context.Context, owner string, repo string, opts github.ListIssuesOptions) ([]*github.IssueData, error)

	// ListPullRequestsFunc mocks the ListPullRequests method.
	ListPullRequestsFunc func(ctx context.Context, owner string, repo string, opts github.ListPullRequestsOptions) ([]*github.PullRequestData, error)

	// ListRepositoriesFunc mocks the ListRepositories method.
	ListRepositoriesFunc func(ctx context.Context, owner string, opts github.ListOptions) ([]*github.RepositoryData, error)

	// ListWorkflowRunsFunc mocks the ListWorkflowRuns method.
	ListWorkflowRunsFunc func(ctx context.Context, owner string, repo string, opts github.ListWorkflowRunsOptions) ([]*github.WorkflowRunData, error)

	// MergePullRequestFunc mocks the MergePullRequest method.
	MergePullRequestFunc func(ctx context.Context, owner string, repo string, number int, opts github.MergePullRequestOptions) error

	// RemoveLabelFunc mocks the RemoveLabel method.
	RemoveLabelFunc func(ctx context.Context, owner string, repo string, number int, label string) error

	// TriggerWorkflowFunc mocks the TriggerWorkflow method.
	TriggerWorkflowFunc func(ctx context.Context, owner string, repo string, workflowFileName string, ref string, inputs map[string]interface{}) error

	// UpdateIssueFunc mocks the UpdateIssue method.
	UpdateIssueFunc func(ctx context.Context, owner string, repo string, number int, opts github.UpdateIssueOptions) (*github.IssueData, error)

	// UpdatePullRequestFunc mocks the UpdatePullRequest method.
	UpdatePullRequestFunc func(ctx context.Context, owner string, repo string, number int, opts github.UpdatePullRequestOptions) (*github.PullRequestData, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddLabels holds details about calls to the AddLabels method.
		AddLabels []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Number is the number argument value.
			Number int
			// Labels is the labels argument value.
			Labels []string
		}
		// CloseIssue holds details about calls to the CloseIssue method.
		CloseIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Number is the number argument value.
			Number int
		}
		// CreateIssue holds details about calls to the CreateIssue method.
		CreateIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Opts is the opts argument value.
			Opts github.CreateIssueOptions
		}
		// CreatePullRequest holds details about calls to the CreatePullRequest method.
		CreatePullRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Opts is the opts argument value.
			Opts github.CreatePullRequestOptions
		}
		// CreateRepository holds details about calls to the CreateRepository method.
		CreateRepository []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Opts is the opts argument value.
			Opts github.CreateRepositoryOptions
		}
		// GetIssue holds details about calls to the GetIssue method.
		GetIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Number is the number argument value.
			Number int
		}
		// GetPullRequest holds details about calls to the GetPullRequest method.
		GetPullRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Number is the number argument value.
			Number int
		}
		// GetRepository holds details about calls to the GetRepository method.
		GetRepository []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
		}
		// GetWorkflowRun holds details about calls to the GetWorkflowRun method.
		GetWorkflowRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// RunID is the runID argument value.
			RunID int64
		}
		// GetWorkflowRunJobs holds details about calls to the GetWorkflowRunJobs method.
		GetWorkflowRunJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// RunID is the runID argument value.
			RunID int64
		}
		// ListIssues holds details about calls to the ListIssues method.
		ListIssues []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Opts is the opts argument value.
			Opts github.ListIssuesOptions
		}
		// ListPullRequests holds details about calls to the ListPullRequests method.
		ListPullRequests []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Opts is the opts argument value.
			Opts github.ListPullRequestsOptions
		}
		// ListRepositories holds details about calls to the ListRepositories method.
		ListRepositories []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Opts is the opts argument value.
			Opts github.ListOptions
		}
		// ListWorkflowRuns holds details about calls to the ListWorkflowRuns method.
		ListWorkflowRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Opts is the opts argument value.
			Opts github.ListWorkflowRunsOptions
		}
		// MergePullRequest holds details about calls to the MergePullRequest method.
		MergePullRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Number is the number argument value.
			Number int
			// Opts is the opts argument value.
			Opts github.MergePullRequestOptions
		}
		// RemoveLabel holds details about calls to the RemoveLabel method.
		RemoveLabel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Number is the number argument value.
			Number int
			// Label is the label argument value.
			Label string
		}
		// TriggerWorkflow holds details about calls to the TriggerWorkflow method.
		TriggerWorkflow []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// WorkflowFileName is the workflowFileName argument value.
			WorkflowFileName string
			// Ref is the ref argument value.
			Ref string
			// Inputs is the inputs argument value.
			Inputs map[string]interface{}
		}
		// UpdateIssue holds details about calls to the UpdateIssue method.
		UpdateIssue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Number is the number argument value.
			Number int
			// Opts is the opts argument value.
			Opts github.UpdateIssueOptions
		}
		// UpdatePullRequest holds details about calls to the UpdatePullRequest method.
		UpdatePullRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Owner is the owner argument value.
			Owner string
			// Repo is the repo argument value.
			Repo string
			// Number is the number argument value.
			Number int
			// Opts is the opts argument value.
			Opts github.UpdatePullRequestOptions
		}
	}
	lockAddLabels          sync.RWMutex
	lockCloseIssue         sync.RWMutex
	lockCreateIssue        sync.RWMutex
	lockCreatePullRequest  sync.RWMutex
	lockCreateRepository   sync.RWMutex
	lockGetIssue           sync.RWMutex
	lockGetPullRequest     sync.RWMutex
	lockGetRepository      sync.RWMutex
	lockGetWorkflowRun     sync.RWMutex
	lockGetWorkflowRunJobs sync.RWMutex
	lockListIssues         sync.RWMutex
	lockListPullRequests   sync.RWMutex
	lockListRepositories   sync.RWMutex
	lockListWorkflowRuns   sync.RWMutex
	lockMergePullRequest   sync.RWMutex
	lockRemoveLabel        sync.RWMutex
	lockTriggerWorkflow    sync.RWMutex
	lockUpdateIssue        sync.RWMutex
	lockUpdatePullRequest  sync.RWMutex
}

// AddLabels calls AddLabelsFunc.
func (mock *ProviderMock) AddLabels(ctx context.Context, owner string, repo string, number int, labels []string) error {
	if mock.AddLabelsFunc == nil {
		panic("ProviderMock.AddLabelsFunc: method is nil but Provider.AddLabels was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Labels []string
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Number: number,
		Labels: labels,
	}
	mock.lockAddLabels.Lock()
	mock.calls.AddLabels = append(mock.calls.AddLabels, callInfo)
	mock.lockAddLabels.Unlock()
	return mock.AddLabelsFunc(ctx, owner, repo, number, labels)
}

// AddLabelsCalls gets all the calls that were made to AddLabels.
// Check the length with:
//
//	len(mockedProvider.AddLabelsCalls())
func (mock *ProviderMock) AddLabelsCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Number int
	Labels []string
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Labels []string
	}
	mock.lockAddLabels.RLock()
	calls = mock.calls.AddLabels
	mock.lockAddLabels.RUnlock()
	return calls
}

// CloseIssue calls CloseIssueFunc.
func (mock *ProviderMock) CloseIssue(ctx context.Context, owner string, repo string, number int) error {
	if mock.CloseIssueFunc == nil {
		panic("ProviderMock.CloseIssueFunc: method is nil but Provider.CloseIssue was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Number: number,
	}
	mock.lockCloseIssue.Lock()
	mock.calls.CloseIssue = append(mock.calls.CloseIssue, callInfo)
	mock.lockCloseIssue.Unlock()
	return mock.CloseIssueFunc(ctx, owner, repo, number)
}

// CloseIssueCalls gets all the calls that were made to CloseIssue.
// Check the length with:
//
//	len(mockedProvider.CloseIssueCalls())
func (mock *ProviderMock) CloseIssueCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Number int
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
	}
	mock.lockCloseIssue.RLock()
	calls = mock.calls.CloseIssue
	mock.lockCloseIssue.RUnlock()
	return calls
}

// CreateIssue calls CreateIssueFunc.
func (mock *ProviderMock) CreateIssue(ctx context.Context, owner string, repo string, opts github.CreateIssueOptions) (*github.IssueData, error) {
	if mock.CreateIssueFunc == nil {
		panic("ProviderMock.CreateIssueFunc: method is nil but Provider.CreateIssue was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.CreateIssueOptions
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
		Opts:  opts,
	}
	mock.lockCreateIssue.Lock()
	mock.calls.CreateIssue = append(mock.calls.CreateIssue, callInfo)
	mock.lockCreateIssue.Unlock()
	return mock.CreateIssueFunc(ctx, owner, repo, opts)
}

// CreateIssueCalls gets all the calls that were made to CreateIssue.
// Check the length with:
//
//	len(mockedProvider.CreateIssueCalls())
func (mock *ProviderMock) CreateIssueCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
	Opts  github.CreateIssueOptions
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.CreateIssueOptions
	}
	mock.lockCreateIssue.RLock()
	calls = mock.calls.CreateIssue
	mock.lockCreateIssue.RUnlock()
	return calls
}

// CreatePullRequest calls CreatePullRequestFunc.
func (mock *ProviderMock) CreatePullRequest(ctx context.Context, owner string, repo string, opts github.CreatePullRequestOptions) (*github.PullRequestData, error) {
	if mock.CreatePullRequestFunc == nil {
		panic("ProviderMock.CreatePullRequestFunc: method is nil but Provider.CreatePullRequest was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.CreatePullRequestOptions
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
		Opts:  opts,
	}
	mock.lockCreatePullRequest.Lock()
	mock.calls.CreatePullRequest = append(mock.calls.CreatePullRequest, callInfo)
	mock.lockCreatePullRequest.Unlock()
	return mock.CreatePullRequestFunc(ctx, owner, repo, opts)
}

// CreatePullRequestCalls gets all the calls that were made to CreatePullRequest.
// Check the length with:
//
//	len(mockedProvider.CreatePullRequestCalls())
func (mock *ProviderMock) CreatePullRequestCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
	Opts  github.CreatePullRequestOptions
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.CreatePullRequestOptions
	}
	mock.lockCreatePullRequest.RLock()
	calls = mock.calls.CreatePullRequest
	mock.lockCreatePullRequest.RUnlock()
	return calls
}

// CreateRepository calls CreateRepositoryFunc.
func (mock *ProviderMock) CreateRepository(ctx context.Context, owner string, opts github.CreateRepositoryOptions) (*github.RepositoryData, error) {
	if mock.CreateRepositoryFunc == nil {
		panic("ProviderMock.CreateRepositoryFunc: method is nil but Provider.CreateRepository was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Opts  github.CreateRepositoryOptions
	}{
		Ctx:   ctx,
		Owner: owner,
		Opts:  opts,
	}
	mock.lockCreateRepository.Lock()
	mock.calls.CreateRepository = append(mock.calls.CreateRepository, callInfo)
	mock.lockCreateRepository.Unlock()
	return mock.CreateRepositoryFunc(ctx, owner, opts)
}

// CreateRepositoryCalls gets all the calls that were made to CreateRepository.
// Check the length with:
//
//	len(mockedProvider.CreateRepositoryCalls())
func (mock *ProviderMock) CreateRepositoryCalls() []struct {
	Ctx   context.Context
	Owner string
	Opts  github.CreateRepositoryOptions
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Opts  github.CreateRepositoryOptions
	}
	mock.lockCreateRepository.RLock()
	calls = mock.calls.CreateRepository
	mock.lockCreateRepository.RUnlock()
	return calls
}

// GetIssue calls GetIssueFunc.
func (mock *ProviderMock) GetIssue(ctx context.Context, owner string, repo string, number int) (*github.IssueData, error) {
	if mock.GetIssueFunc == nil {
		panic("ProviderMock.GetIssueFunc: method is nil but Provider.GetIssue was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Number: number,
	}
	mock.lockGetIssue.Lock()
	mock.calls.GetIssue = append(mock.calls.GetIssue, callInfo)
	mock.lockGetIssue.Unlock()
	return mock.GetIssueFunc(ctx, owner, repo, number)
}

// GetIssueCalls gets all the calls that were made to GetIssue.
// Check the length with:
//
//	len(mockedProvider.GetIssueCalls())
func (mock *ProviderMock) GetIssueCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Number int
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
	}
	mock.lockGetIssue.RLock()
	calls = mock.calls.GetIssue
	mock.lockGetIssue.RUnlock()
	return calls
}

// GetPullRequest calls GetPullRequestFunc.
func (mock *ProviderMock) GetPullRequest(ctx context.Context, owner string, repo string, number int) (*github.PullRequestData, error) {
	if mock.GetPullRequestFunc == nil {
		panic("ProviderMock.GetPullRequestFunc: method is nil but Provider.GetPullRequest was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Number: number,
	}
	mock.lockGetPullRequest.Lock()
	mock.calls.GetPullRequest = append(mock.calls.GetPullRequest, callInfo)
	mock.lockGetPullRequest.Unlock()
	return mock.GetPullRequestFunc(ctx, owner, repo, number)
}

// GetPullRequestCalls gets all the calls that were made to GetPullRequest.
// Check the length with:
//
//	len(mockedProvider.GetPullRequestCalls())
func (mock *ProviderMock) GetPullRequestCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Number int
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
	}
	mock.lockGetPullRequest.RLock()
	calls = mock.calls.GetPullRequest
	mock.lockGetPullRequest.RUnlock()
	return calls
}

// GetRepository calls GetRepositoryFunc.
func (mock *ProviderMock) GetRepository(ctx context.Context, owner string, repo string) (*github.RepositoryData, error) {
	if mock.GetRepositoryFunc == nil {
		panic("ProviderMock.GetRepositoryFunc: method is nil but Provider.GetRepository was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
	}
	mock.lockGetRepository.Lock()
	mock.calls.GetRepository = append(mock.calls.GetRepository, callInfo)
	mock.lockGetRepository.Unlock()
	return mock.GetRepositoryFunc(ctx, owner, repo)
}

// GetRepositoryCalls gets all the calls that were made to GetRepository.
// Check the length with:
//
//	len(mockedProvider.GetRepositoryCalls())
func (mock *ProviderMock) GetRepositoryCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
	}
	mock.lockGetRepository.RLock()
	calls = mock.calls.GetRepository
	mock.lockGetRepository.RUnlock()
	return calls
}

// GetWorkflowRun calls GetWorkflowRunFunc.
func (mock *ProviderMock) GetWorkflowRun(ctx context.Context, owner string, repo string, runID int64) (*github.WorkflowRunData, error) {
	if mock.GetWorkflowRunFunc == nil {
		panic("ProviderMock.GetWorkflowRunFunc: method is nil but Provider.GetWorkflowRun was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
		RunID int64
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
		RunID: runID,
	}
	mock.lockGetWorkflowRun.Lock()
	mock.calls.GetWorkflowRun = append(mock.calls.GetWorkflowRun, callInfo)
	mock.lockGetWorkflowRun.Unlock()
	return mock.GetWorkflowRunFunc(ctx, owner, repo, runID)
}

// GetWorkflowRunCalls gets all the calls that were made to GetWorkflowRun.
// Check the length with:
//
//	len(mockedProvider.GetWorkflowRunCalls())
func (mock *ProviderMock) GetWorkflowRunCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
	RunID int64
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
		RunID int64
	}
	mock.lockGetWorkflowRun.RLock()
	calls = mock.calls.GetWorkflowRun
	mock.lockGetWorkflowRun.RUnlock()
	return calls
}

// GetWorkflowRunJobs calls GetWorkflowRunJobsFunc.
func (mock *ProviderMock) GetWorkflowRunJobs(ctx context.Context, owner string, repo string, runID int64) ([]*github.WorkflowJobData, error) {
	if mock.GetWorkflowRunJobsFunc == nil {
		panic("ProviderMock.GetWorkflowRunJobsFunc: method is nil but Provider.GetWorkflowRunJobs was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
		RunID int64
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
		RunID: runID,
	}
	mock.lockGetWorkflowRunJobs.Lock()
	mock.calls.GetWorkflowRunJobs = append(mock.calls.GetWorkflowRunJobs, callInfo)
	mock.lockGetWorkflowRunJobs.Unlock()
	return mock.GetWorkflowRunJobsFunc(ctx, owner, repo, runID)
}

// GetWorkflowRunJobsCalls gets all the calls that were made to GetWorkflowRunJobs.
// Check the length with:
//
//	len(mockedProvider.GetWorkflowRunJobsCalls())
func (mock *ProviderMock) GetWorkflowRunJobsCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
	RunID int64
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
		RunID int64
	}
	mock.lockGetWorkflowRunJobs.RLock()
	calls = mock.calls.GetWorkflowRunJobs
	mock.lockGetWorkflowRunJobs.RUnlock()
	return calls
}

// ListIssues calls ListIssuesFunc.
func (mock *ProviderMock) ListIssues(ctx context.Context, owner string, repo string, opts github.ListIssuesOptions) ([]*github.IssueData, error) {
	if mock.ListIssuesFunc == nil {
		panic("ProviderMock.ListIssuesFunc: method is nil but Provider.ListIssues was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.ListIssuesOptions
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
		Opts:  opts,
	}
	mock.lockListIssues.Lock()
	mock.calls.ListIssues = append(mock.calls.ListIssues, callInfo)
	mock.lockListIssues.Unlock()
	return mock.ListIssuesFunc(ctx, owner, repo, opts)
}

// ListIssuesCalls gets all the calls that were made to ListIssues.
// Check the length with:
//
//	len(mockedProvider.ListIssuesCalls())
func (mock *ProviderMock) ListIssuesCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
	Opts  github.ListIssuesOptions
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.ListIssuesOptions
	}
	mock.lockListIssues.RLock()
	calls = mock.calls.ListIssues
	mock.lockListIssues.RUnlock()
	return calls
}

// ListPullRequests calls ListPullRequestsFunc.
func (mock *ProviderMock) ListPullRequests(ctx context.Context, owner string, repo string, opts github.ListPullRequestsOptions) ([]*github.PullRequestData, error) {
	if mock.ListPullRequestsFunc == nil {
		panic("ProviderMock.ListPullRequestsFunc: method is nil but Provider.ListPullRequests was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.ListPullRequestsOptions
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
		Opts:  opts,
	}
	mock.lockListPullRequests.Lock()
	mock.calls.ListPullRequests = append(mock.calls.ListPullRequests, callInfo)
	mock.lockListPullRequests.Unlock()
	return mock.ListPullRequestsFunc(ctx, owner, repo, opts)
}

// ListPullRequestsCalls gets all the calls that were made to ListPullRequests.
// Check the length with:
//
//	len(mockedProvider.ListPullRequestsCalls())
func (mock *ProviderMock) ListPullRequestsCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
	Opts  github.ListPullRequestsOptions
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.ListPullRequestsOptions
	}
	mock.lockListPullRequests.RLock()
	calls = mock.calls.ListPullRequests
	mock.lockListPullRequests.RUnlock()
	return calls
}

// ListRepositories calls ListRepositoriesFunc.
func (mock *ProviderMock) ListRepositories(ctx context.Context, owner string, opts github.ListOptions) ([]*github.RepositoryData, error) {
	if mock.ListRepositoriesFunc == nil {
		panic("ProviderMock.ListRepositoriesFunc: method is nil but Provider.ListRepositories was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Opts  github.ListOptions
	}{
		Ctx:   ctx,
		Owner: owner,
		Opts:  opts,
	}
	mock.lockListRepositories.Lock()
	mock.calls.ListRepositories = append(mock.calls.ListRepositories, callInfo)
	mock.lockListRepositories.Unlock()
	return mock.ListRepositoriesFunc(ctx, owner, opts)
}

// ListRepositoriesCalls gets all the calls that were made to ListRepositories.
// Check the length with:
//
//	len(mockedProvider.ListRepositoriesCalls())
func (mock *ProviderMock) ListRepositoriesCalls() []struct {
	Ctx   context.Context
	Owner string
	Opts  github.ListOptions
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Opts  github.ListOptions
	}
	mock.lockListRepositories.RLock()
	calls = mock.calls.ListRepositories
	mock.lockListRepositories.RUnlock()
	return calls
}

// ListWorkflowRuns calls ListWorkflowRunsFunc.
func (mock *ProviderMock) ListWorkflowRuns(ctx context.Context, owner string, repo string, opts github.ListWorkflowRunsOptions) ([]*github.WorkflowRunData, error) {
	if mock.ListWorkflowRunsFunc == nil {
		panic("ProviderMock.ListWorkflowRunsFunc: method is nil but Provider.ListWorkflowRuns was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.ListWorkflowRunsOptions
	}{
		Ctx:   ctx,
		Owner: owner,
		Repo:  repo,
		Opts:  opts,
	}
	mock.lockListWorkflowRuns.Lock()
	mock.calls.ListWorkflowRuns = append(mock.calls.ListWorkflowRuns, callInfo)
	mock.lockListWorkflowRuns.Unlock()
	return mock.ListWorkflowRunsFunc(ctx, owner, repo, opts)
}

// ListWorkflowRunsCalls gets all the calls that were made to ListWorkflowRuns.
// Check the length with:
//
//	len(mockedProvider.ListWorkflowRunsCalls())
func (mock *ProviderMock) ListWorkflowRunsCalls() []struct {
	Ctx   context.Context
	Owner string
	Repo  string
	Opts  github.ListWorkflowRunsOptions
} {
	var calls []struct {
		Ctx   context.Context
		Owner string
		Repo  string
		Opts  github.ListWorkflowRunsOptions
	}
	mock.lockListWorkflowRuns.RLock()
	calls = mock.calls.ListWorkflowRuns
	mock.lockListWorkflowRuns.RUnlock()
	return calls
}

// MergePullRequest calls MergePullRequestFunc.
func (mock *ProviderMock) MergePullRequest(ctx context.Context, owner string, repo string, number int, opts github.MergePullRequestOptions) error {
	if mock.MergePullRequestFunc == nil {
		panic("ProviderMock.MergePullRequestFunc: method is nil but Provider.MergePullRequest was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Opts   github.MergePullRequestOptions
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Number: number,
		Opts:   opts,
	}
	mock.lockMergePullRequest.Lock()
	mock.calls.MergePullRequest = append(mock.calls.MergePullRequest, callInfo)
	mock.lockMergePullRequest.Unlock()
	return mock.MergePullRequestFunc(ctx, owner, repo, number, opts)
}

// MergePullRequestCalls gets all the calls that were made to MergePullRequest.
// Check the length with:
//
//	len(mockedProvider.MergePullRequestCalls())
func (mock *ProviderMock) MergePullRequestCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Number int
	Opts   github.MergePullRequestOptions
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Opts   github.MergePullRequestOptions
	}
	mock.lockMergePullRequest.RLock()
	calls = mock.calls.MergePullRequest
	mock.lockMergePullRequest.RUnlock()
	return calls
}

// RemoveLabel calls RemoveLabelFunc.
func (mock *ProviderMock) RemoveLabel(ctx context.Context, owner string, repo string, number int, label string) error {
	if mock.RemoveLabelFunc == nil {
		panic("ProviderMock.RemoveLabelFunc: method is nil but Provider.RemoveLabel was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Label  string
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Number: number,
		Label:  label,
	}
	mock.lockRemoveLabel.Lock()
	mock.calls.RemoveLabel = append(mock.calls.RemoveLabel, callInfo)
	mock.lockRemoveLabel.Unlock()
	return mock.RemoveLabelFunc(ctx, owner, repo, number, label)
}

// RemoveLabelCalls gets all the calls that were made to RemoveLabel.
// Check the length with:
//
//	len(mockedProvider.RemoveLabelCalls())
func (mock *ProviderMock) RemoveLabelCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Number int
	Label  string
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Label  string
	}
	mock.lockRemoveLabel.RLock()
	calls = mock.calls.RemoveLabel
	mock.lockRemoveLabel.RUnlock()
	return calls
}

// TriggerWorkflow calls TriggerWorkflowFunc.
func (mock *ProviderMock) TriggerWorkflow(ctx context.Context, owner string, repo string, workflowFileName string, ref string, inputs map[string]interface{}) error {
	if mock.TriggerWorkflowFunc == nil {
		panic("ProviderMock.TriggerWorkflowFunc: method is nil but Provider.TriggerWorkflow was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		Owner            string
		Repo             string
		WorkflowFileName string
		Ref              string
		Inputs           map[string]interface{}
	}{
		Ctx:              ctx,
		Owner:            owner,
		Repo:             repo,
		WorkflowFileName: workflowFileName,
		Ref:              ref,
		Inputs:           inputs,
	}
	mock.lockTriggerWorkflow.Lock()
	mock.calls.TriggerWorkflow = append(mock.calls.TriggerWorkflow, callInfo)
	mock.lockTriggerWorkflow.Unlock()
	return mock.TriggerWorkflowFunc(ctx, owner, repo, workflowFileName, ref, inputs)
}

// TriggerWorkflowCalls gets all the calls that were made to TriggerWorkflow.
// Check the length with:
//
//	len(mockedProvider.TriggerWorkflowCalls())
func (mock *ProviderMock) TriggerWorkflowCalls() []struct {
	Ctx              context.Context
	Owner            string
	Repo             string
	WorkflowFileName string
	Ref              string
	Inputs           map[string]interface{}
} {
	var calls []struct {
		Ctx              context.Context
		Owner            string
		Repo             string
		WorkflowFileName string
		Ref              string
		Inputs           map[string]interface{}
	}
	mock.lockTriggerWorkflow.RLock()
	calls = mock.calls.TriggerWorkflow
	mock.lockTriggerWorkflow.RUnlock()
	return calls
}

// UpdateIssue calls UpdateIssueFunc.
func (mock *ProviderMock) UpdateIssue(ctx context.Context, owner string, repo string, number int, opts github.UpdateIssueOptions) (*github.IssueData, error) {
	if mock.UpdateIssueFunc == nil {
		panic("ProviderMock.UpdateIssueFunc: method is nil but Provider.UpdateIssue was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Opts   github.UpdateIssueOptions
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Number: number,
		Opts:   opts,
	}
	mock.lockUpdateIssue.Lock()
	mock.calls.UpdateIssue = append(mock.calls.UpdateIssue, callInfo)
	mock.lockUpdateIssue.Unlock()
	return mock.UpdateIssueFunc(ctx, owner, repo, number, opts)
}

// UpdateIssueCalls gets all the calls that were made to UpdateIssue.
// Check the length with:
//
//	len(mockedProvider.UpdateIssueCalls())
func (mock *ProviderMock) UpdateIssueCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Number int
	Opts   github.UpdateIssueOptions
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Opts   github.UpdateIssueOptions
	}
	mock.lockUpdateIssue.RLock()
	calls = mock.calls.UpdateIssue
	mock.lockUpdateIssue.RUnlock()
	return calls
}

// UpdatePullRequest calls UpdatePullRequestFunc.
func (mock *ProviderMock) UpdatePullRequest(ctx context.Context, owner string, repo string, number int, opts github.UpdatePullRequestOptions) (*github.PullRequestData, error) {
	if mock.UpdatePullRequestFunc == nil {
		panic("ProviderMock.UpdatePullRequestFunc: method is nil but Provider.UpdatePullRequest was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Opts   github.UpdatePullRequestOptions
	}{
		Ctx:    ctx,
		Owner:  owner,
		Repo:   repo,
		Number: number,
		Opts:   opts,
	}
	mock.lockUpdatePullRequest.Lock()
	mock.calls.UpdatePullRequest = append(mock.calls.UpdatePullRequest, callInfo)
	mock.lockUpdatePullRequest.Unlock()
	return mock.UpdatePullRequestFunc(ctx, owner, repo, number, opts)
}

// UpdatePullRequestCalls gets all the calls that were made to UpdatePullRequest.
// Check the length with:
//
//	len(mockedProvider.UpdatePullRequestCalls())
func (mock *ProviderMock) UpdatePullRequestCalls() []struct {
	Ctx    context.Context
	Owner  string
	Repo   string
	Number int
	Opts   github.UpdatePullRequestOptions
} {
	var calls []struct {
		Ctx    context.Context
		Owner  string
		Repo   string
		Number int
		Opts   github.UpdatePullRequestOptions
	}
	mock.lockUpdatePullRequest.RLock()
	calls = mock.calls.UpdatePullRequest
	mock.lockUpdatePullRequest.RUnlock()
	return calls
}
